name: 'release bbp action'
description: 'release plugins for bbki.ng'
author: 'bbki.ng'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: add target
      run: rustup target add wasm32-unknown-unknown
      shell: bash
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      shell: bash
    - name: release
      uses: './actions/release'
      with:
        wasmArtifactName: wasm-file
        wasmFileName: bbp_now.wasm
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        OSS_BUCKET_ENDPOINT: ${{ secrets.OSS_BUCKET_ENDPOINT }}
        OSS_REGION: ${{ secrets.OSS_REGION }}

branding:
  icon: 'coffee'
  color: 'gray-dark'
