name: 'release bbp action'
description: 'release plugins for bbki.ng'
author: 'bbki.ng'
inputs:
  hcp_client_id:
    description: 'The client id of hcp'
    required: true
  hcp_client_secret:
    description: 'The client secret of hcp'
    required: true
  wasm:
    description: 'The name of wasm file (eg. bbp_now.wasm)'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'coffee'
  color: 'gray-dark'
