name: 'release bbp action'
description: 'release plugins for bbki.ng'
inputs:
  configArtifactName:
    description: 'The name of the artifact to use for the configuration'
    required: false
    default: 'plugin-config'
  configFileName:
    description: 'The name of the configuration file'
    required: false
    default: 'plugin.json'
  wasmArtifactName:
    description: 'The name of the artifact to use for the wasm'
    required: true
  wasmFileName:
    description: 'The name of the wasm file after build'
    required: true
  
runs:
  using: 'node20'
  main: 'dist/index.js'
