name: 'release bbp action'
description: 'release plugins for bbki.ng'
author: 'bbki.ng'
inputs:
  token:
    description: 'The token of vercel'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'coffee'
  color: 'gray-dark'
