name: 'release bbp action'
description: 'release plugins for bbki.ng'
author: 'bbki.ng'
inputs:
  vercelToken:
    description: 'The token of vercel'
    required: true

runs:
    using: 'node20'
    main: 'dist/index.js'
